version: '3'
services:
  #Nginx Service
  webserver:
    image: nginx
    depends_on:
       - app
       - db
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    command: [ nginx-debug, '-g', 'daemon off;' ]
    container_name: web-api
    ports:
      - "8084:80"
    networks:
      - api-network
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-api
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - api-network

  #MySQL Service
  db:
    image: mysql:8.0.22
    container_name: db-api
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    ports:
      - "3304:3306"
    environment:
      MYSQL_DATABASE: exercise
      MYSQL_ROOT_PASSWORD: pass
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdataapi:/var/lib/mysql/
    networks:
      - api-network

#Docker Networks
networks:
  api-network:
    driver: bridge
#Volumes
volumes:
  dbdataapi:
    driver: local
